### ISSUE TITLE
opentelemetry-exporter-otlp is not getting installed on aws lamdba

### ISSUE THREAD

**Issue by anubhav6663** [open-telemetry/opentelemetry-ruby#1142]
We are trying to export traces using opentelemetry-exporter-otlp in our application. When we deploy it on lambda, it gives below error. 
`could not find 'google-protobuf' (~> 3.7) among 413 total gem(s)\nChecked in 'GEM_PATH=/var/task/vendor/bundle/ruby/2.7.0:/opt/ruby/gems/2.7.0:/var/runtime' at: /opt/ruby/gems/2.7.0/specifications/opentelemetry-exporter-otlp-0.21.2.gemspec, execute `gem env` for more information",
  "errorType": "Init<Gem::MissingSpecError>`
 
GEMFILE
```
`source 'https://rubygems.org'

gem "opentelemetry-api"
gem "opentelemetry-sdk"
gem "opentelemetry-exporter-otlp"
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-resource_detectors'
gem 'opentelemetry-instrumentation-aws_sdk'
gem "functions_framework"
gem "rest-client"`
```

When we do bundle install  it is installing google-protobuf (3.19.4) in vendor directory.

GEMFILE.lock contains something like:
```

`opentelemetry-exporter-otlp (0.21.2)
      google-protobuf (~> 3.7)
      opentelemetry-api (~> 1.0)
      opentelemetry-common (~> 0.19.3)
      opentelemetry-sdk (~> 1.0)`
```

*Potential Solution*
Update:     
https://github.com/open-telemetry/opentelemetry-ruby/blob/06b36a646afb30e86ad426f1be2bc97ed269fa15/exporter/otlp/opentelemetry-exporter-otlp.gemspec#L28

**Comment by ericmustin** [comment]
@anubhav6663 Thanks for reaching out.

I'll preface this by saying I am very much not a lambda power user, and don't have easy access to AWS environments to reproduce this (I worked at a mostly gcp shop 🙃 ), so apologies if I have misunderstood some concepts here.

I looked into this a bit and one thing that stuck out to me is that, is it possible that your local development environment's Ruby version where `Gemfile.lock` was added, is different than the Lambda Ruby version (2.7)?

This delta seems like a [common root cause](https://stackoverflow.com/questions/53673486/aws-lambda-ruby-function-failing-to-load-gem) of the error you're facing.

Would it be possible to verify that your local and lambda development environments match?

cc @Aneurysm9 👋 is there someone from your team a bit more familiar with debugging lambdas, in case the above is incorrect?

**Comment by anubhav6663** [comment]
@ericmustin  Thanks for response.
I was able to resole this issue. This is happening because google-protbuf is platform dependent gem. 
I am building the gems on mac( darwin) , and lambda's default is linux. 
`bundle install` on mac generates `google-protobuf-3.19.4-x86_64-darwin` gem, but aws lambda looks for linux based gem `google-protobuf-3.19.3-x86_64-linux`. 
For aws lambda we have to build and install on linux based system, and them build a layer.
