### ISSUE TITLE
Support `jaeger_remote` sampling strategy

### ISSUE THREAD

**Issue by ahayworth** [open-telemetry/opentelemetry-ruby#1252]
Added in: https://github.com/open-telemetry/opentelemetry-specification/pull/1791
More info in: https://github.com/open-telemetry/opentelemetry-specification/pull/2222
More info in: https://github.com/open-telemetry/opentelemetry-specification/pull/2246

The `jaeger_remote` sampling strategy appears to be a sampling strategy that is dictated by a GRPC service that provides sampling details to the tracer.

This may be complicated, and I'm not sure that it should be prioritized without any definitive desire from our users.

**Comment by gouthamve** [comment]
Okay, so I took a stab at implementing this, and it turns out it's pretty hard. The main reason is that the `span.name` passed to the sampler and the final name exported are different. :( 

If you have an application that uses Rack with Sinatra, Rack will create the span with `name=HTTP GET` and this span will be passed to the sampler for the sampling decision.

But then sometime later Sinatra does the route matching and updates the name to `GET /books/` here: https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/sinatra/lib/opentelemetry/instrumentation/sinatra/middlewares/tracer_middleware.rb#L26-L29

Essentially ALL spans get sent to the sampler as `HTTP GET` and it's not possible to differentiate on a per route level. We could potentially do it using `attributes` but that seems brittle.

Now I don't know to do sampling based on the root span name anymore :(

**Comment by gouthamve** [comment]
I'd love to contribute. I modeled my custom sampler on the xray sampler and it is very similar in structure. I made good headway before hitting this roadblock.

Being able to control sampling on a per-endpoint level unlocked a lot of value for us previously and I'd love to use it again for a different project. For a little more context, I wrote my rationale here: https://www.gouthamve.dev/sampling-is-tracings-weakness/

**Comment by kaylareopelle** [comment]
Hi @gouthamve, thanks for working on this! Like Eric said, we'll talk about this more during the SIG. 

In the meantime, since it seems like the new sampler should live in contrib, my vote is to have an issue in that repo to track future work.
