### ISSUE TITLE
Is it possible to add attributes to "instrumentation scope"?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-ruby#1262]
[This OTEP](https://github.com/open-telemetry/oteps/pull/201) proposed to add attributes to instrumentation scope.

This issue is a question for the maintainers of this repo: are we able to do this in a non-breaking manner and without significant performance impact?

**Comment by ahayworth** [comment]
I think that it's likely possible, yes - if I understand that OTEP correctly, the attributes would be added to the instrumentation scope when obtaining a tracer. Since that happens infrequently, I suspect it will not be a huge problem.

However, if any other @open-telemetry/ruby-approvers or @open-telemetry/ruby-maintainers want to chime in, that would be excellent.

**Comment by fbogsany** [comment]
We would need to add an optional parameter to the API here: https://github.com/open-telemetry/opentelemetry-ruby/blob/113e5133afd7a42c30273d860330008c24530d6d/api/lib/opentelemetry/trace/tracer_provider.rb#L17 and to the SDK here: https://github.com/open-telemetry/opentelemetry-ruby/blob/113e5133afd7a42c30273d860330008c24530d6d/sdk/lib/opentelemetry/sdk/trace/tracer_provider.rb#L51

The SDK `Tracer` initializer is marked API-private, so any changes there are backwards compatible. We will need to add the attributes to `Scope` (which is still `InstrumentationLibrary` for us), but that will be backwards compatible as well.

**Comment by tigrannajaryan** [comment]
Thank you @ahayworth @fbogsany 
I will close this, since all I needed for now was a confirmation.
