### ISSUE TITLE
unexpected error decoding rpc.Status when 401

### ISSUE THREAD

**Issue by shaul75** [open-telemetry/opentelemetry-ruby#1348]
**Description of the bug**
When the OTLP HTTP exporter receives 401 unauthorized from the collector:
```
E, [2022-07-26T16:48:17.742186 #13635] ERROR -- : OpenTelemetry error: unexpected error decoding rpc.Status in OTLP::Exporter#log_status - Error occurred during parsing
```

The problem seem to be caused by a feature introduced in  https://github.com/open-telemetry/opentelemetry-ruby/pull/1152

I don't understand why is `Google::Rpc::Status` being used to parse the response in that log method. There's only the HTTP protocol exporter, not the gRPC one?

**Comment by fbogsany** [comment]
[The OTLP/HTTP part of the spec unambiguously states](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#failures-1)
> Response body for all HTTP 4xx and HTTP 5xx responses MUST be a Protobuf-encoded [Status](https://godoc.org/google.golang.org/genproto/googleapis/rpc/status#Status) message that describes the problem.

Originally, this was not implemented correctly in the OTLP collector. This was fixed in https://github.com/open-telemetry/opentelemetry-collector/pull/1788. Are you using an old version of the collector, or a 3rd-party collector?
