### ISSUE TITLE
Decode values from `OTEL_RESOURCE_ATTRIBUTES`

### ISSUE THREAD

**Issue by lgfa29** [open-telemetry/opentelemetry-ruby#1352]
While using the Go SDK I noticed an inconsistency in how `OTEL_RESOURCE_ATTRIBUTES` baggage values are encoded and decoded. This was due to a difference in the version of the W3C Baggage spec used for [baggage propagation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#propagation) and the [`OTEL_RESOURCE_ATTRIBUTES` decoding](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable).

https://github.com/open-telemetry/opentelemetry-specification/pull/2670 updates the W3C Baggage spec version used by the Resource spec to require percent-decoding values from  `OTEL_RESOURCE_ATTRIBUTES`.

**Comment by ahayworth** [comment]
I haven't parsed [the differences](https://github.com/w3c/baggage/compare/fdc7a5c4f4a31ba2a36717541055e551c2b032e4..main#diff-f65e951e116caf027fff48025b09977ad3539456579743d5c8018b9313484229) between the versions of the W3C spec in question... but if it turns out that the current decoding logic in the [baggage text-map propagator](https://github.com/open-telemetry/opentelemetry-ruby/blob/6fed21de005917f1900a8b8dc879f89623e4c61a/api/lib/opentelemetry/baggage/propagation/text_map_propagator.rb#L66) is correct then this would be a relatively easy change for us to make (thank you `CGI.unescape`!).

However, we should wait until the spec change is accepted. Once it is, we can definitely address this. Thank you for the heads-up, I'll add this to our spec-compliance tracking project. ❤️ 🙇

**Comment by lgfa29** [comment]
I think the main change is the requirement to percent-decode values. There are some additional considerations about privacy and security but I think they are mostly targeted at end-users. 

Looking at the code you linked it does seem like that's all that is needed. Here's the relevant Go update as reference: https://github.com/open-telemetry/opentelemetry-go/pull/2963/files#diff-b00b30ddb9242080b6237eb51f35a5120cb88036d6892571a8f430d8f3152e0dR94

One interesting thing I noticed is that the W3C spec mandates that the keys must only contain visible ASCII characters (that's why they don't need percent-decoding), but a had a quick glance at the Otel SDKs and none of them seem to enforce this.

**Comment by robbkidd** [comment]
Noting here that [the spec update](https://github.com/open-telemetry/opentelemetry-specification/pull/2670) has merged to the spec, so we are green-lit for rubbing percents on things.
