### ISSUE TITLE
Improve proto generation rake task

### ISSUE THREAD

**Issue by ahayworth** [open-telemetry/opentelemetry-ruby#1358]
Use `Dir.glob` and clean it up.

_Originally posted by @ahayworth in https://github.com/open-telemetry/opentelemetry-ruby/pull/1345#discussion_r941846248_

**Comment by robbkidd** [comment]
🤔 I've [rediscovered `Rake::FileList`](https://graceful.dev/courses/the-freebies/modules/rake-and-project-automation/topic/episode-130-rake-file-lists/). Because this activity is occurring in a Rakefile, 

```ruby
proto_files = Rake::FileList["opentelemetry-proto/**/*.proto"]
```

… is also an option.

I am resisting trying to write Rake `rule`s for `.proto` to `.pb`. I expect they would end up weird and hard to read.
