### ISSUE TITLE
Allow external exporters in `OTEL_TRACES_EXPORTER`

### ISSUE THREAD

**Issue by jtmalinowski** [open-telemetry/opentelemetry-ruby#1365]
Currently `OpenTelemetry::SDK::Configurator#wrapped_exporters_from_env` uses a hard-coded case-when list of exporters. I'm proposing that we make the list extendable.

A use case for the same easy configuration process (ENV-based) for vendors with their own exporters. For example setting `OTEL_TRACES_EXPORTER=console,otlp-<vendor name>` would enable both the console exporter and an instance of OTLP exporter configured to send data to the vendor.

This idea could be extended to metrics, but I'm not familiar with the current status of metrics.

This idea could be extended to propagators, but I don't currently see a good use case for this, as the list is quite complete. Core team can advise here.

I can submit the PR for this issue, if we agree an a solution.

**Comment by plantfansam** [comment]
@jtmalinowski to make sure I understand, you're saying that the configurator's [`add_span_processor` method](https://github.com/open-telemetry/opentelemetry-ruby/blob/672739120a605c5c14afc48e5aa07d1320443355/sdk/lib/opentelemetry/sdk/configurator.rb#L127) is not a satisfactory solution because a env var-based configuration is more user-friendly?
