### ISSUE TITLE
undefined method 'set tag'

### ISSUE THREAD

**Issue by mstoetzn97** [open-telemetry/opentelemetry-ruby#1410]
**Description of the bug**

We use the auto instrumentation feature to instrument our ruby application. We have followed the documentation and (error) traces are also sent to our backend, but our application is now broken. The application tries to retrieve data via REST from a microservice. This results in the error message:

**_undefined method 'set_tag' for #<OpenTelemetry::SDK::Trace::Span:...>_**

```
module ProductHelper
     def get_ads
          @ads = JSON.parse(Net::HTTP.get_response(URI('http://<microservice:port>/ads')).body)
     end
end
```

**Share details about your runtime**
Running on Docker
Docker Image: ruby:2.7.2-slim-buster
RUBY_ENGINE: "ruby"
RUBY_VERSION: "2.7.2"
RAILS_VERSION: "5.2.5"
PUMA_VERSION: "3.12"
SASS-RAILS_VERSION: "5.0"
JBUILDER_VERSION: "2.5"

**Comment by arielvalentin** [comment]
The OTel SDK for does not have a `set_tag` method, that is what it used to be called in OpenTracing (and maybe OpenCensus). 

In order to enrich OTel spans you must use `set_attribute` or `add_attributes`.

Would you confirm that this is coming from our instrumentation and not from custom code attempting to enrich your the spans with the incorrect method name?

What does the stack trace point you to?

**Comment by mstoetzn97** [comment]
It looks like the error came from another instrumentation library we used before. Thanks.
