### ISSUE TITLE
parentbased_traceidratio and adjusted sample count?

### ISSUE THREAD

**Issue by mhellsten-ml** [open-telemetry/opentelemetry-ruby#1413]
I'm having trouble getting my tooling (Honeycomb OTLP endpoint) to recognize my sample rate and adjust sample counts accordingly. Using either `parentbased_traceidratio` or `traceidratio` that should work, since they are probabalistic approaches, correct? I've seen that the sampling decision is based on the p value in the tracestate, and I assume that's also how the sampling rate is supposed to be detected by tooling.

I'd like to prove that I'm emitting the correct data to the OTLP endpoint, but I'm confused, because when I enable trace output to console, it looks like there are no values in the tracestate. Yet, the sampling rate definitely reduces the emitted data as expected.

Am I doing something wrong? Thanks!

Example console output:
```
trace_id="\xFA\x88\xBD\xF9\xC2\xCA\x9A\x8D\x1F\x8C\xAC2\xD0\x1E g",
trace_flags=#<OpenTelemetry::Trace::TraceFlags:0x00007fcf1b8e9a80 @flags=1>,
tracestate=#<OpenTelemetry::Trace::Tracestate:0x00007fcf18ff4490 @hash={}>
```

Environment variables:
```
OTEL_TRACES_SAMPLER_ARG=0.25
OTEL_TRACES_EXPORTER=console
OTEL_TRACES_SAMPLER=parentbased_traceidratio
```

**Comment by fbogsany** [comment]
The `parentbased_traceidratio` sampler does not interact with `tracestate`. For that, you will need to use the `consistent_probability_based` or `parent_consistent_probability_based` samplers. These are in the `sdk_experimental` package, because they're marked as `experimental` in the spec. They can't be configured through the `OTEL_TRACES_SAMPLER` env var - you'll need to do this in code: https://github.com/open-telemetry/opentelemetry-ruby/blob/3564977bf652e0977796b3f271b0c10728e9f414/sdk_experimental/lib/opentelemetry/sdk/experimental/samplers_patch.rb#L20-L37

**Comment by mhellsten-ml** [comment]
@fbogsany, thank you! 🥇
