### ISSUE TITLE
Error in CompositePropagator#extract can't modify frozen String: "HTTP_traceparent"

### ISSUE THREAD

**Issue by natetarrh** [open-telemetry/opentelemetry-ruby#1463]
When running opentelemetry-common 0.19.7 on Ruby 2.7, Rack env context propagation fails due to a frozen string modification error. #1367 introduced a change to `OpenTelemetry::Common::Propagation::RackEnvGetter` to use string interpolation instead of concatenation. This change was included in [v0.19.7](https://github.com/open-telemetry/opentelemetry-ruby/releases/tag/opentelemetry-common%2Fv0.19.7). This fails with a frozen string error. 

**Share details about your runtime**

RUBY_ENGINE: "ruby"
RUBY_VERSION: "2.7.8"
RUBY_DESCRIPTION: "ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [arm64-darwin22]"

**Share a simplified reproduction if possible**

```
$ ruby -v; ruby --enable-frozen-string-literal -e 'bar = "bar"; foobar = "foo" + bar; puts foobar.upcase!'
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [arm64-darwin22]
FOOBAR

$ ruby --enable-frozen-string-literal -e 'bar = "bar"; foobar = "foo#{bar}"; puts foobar.upcase!'
Traceback (most recent call last):
        1: from -e:1:in `<main>'
-e:1:in `upcase!': can't modify frozen String: "foobar" (FrozenError)
```

**Comment by xuan-cao-swi** [comment]
No sure if this is related, but also it seems cause broken trace for distributed tracing.

**Comment by robertlaurin** [comment]
😞 

Looks to be related to some rubocop updates that are were compatible with Ruby 2.7 https://github.com/open-telemetry/opentelemetry-ruby/pull/1367/files#diff-44a4880c61008b50b9af9e3326bf86c70cdce83dead3cf8709d727abe6e1d332

This isn't great timing as I'm about to push our latest release which drops support for Ruby 2.7 since it has hit EoL.

https://github.com/open-telemetry/opentelemetry-ruby/pull/1459

**Comment by natetarrh** [comment]
We have been maintaining Ruby 2.7 compatibility since AWS Lambda only supported a Ruby 2.7 runtime [until yesterday](https://aws.amazon.com/blogs/compute/ruby-3-2-runtime-now-available-in-aws-lambda/). It would be great to continue supporting that runtime to give users a chance to migrate, although I understand it has been EOL since the end of March.

**Comment by arielvalentin** [comment]
@natetarrh You should be able to pin to an earlier version of the gems which works with Ruby 2.7

I will make sure we put together a matrix to make it easier to setup.

**Comment by jerrysitu** [comment]
> Looks like this issue was patched with the release of [opentelemetry-api 1.2.2](https://github.com/open-telemetry/opentelemetry-ruby/releases/tag/opentelemetry-api%2Fv1.2.2)?

I'm in the same boat and can't upgrade to Ruby 3.0 which this requires

**Comment by gabricc** [comment]
+1 to this. It would be super helpful to have this fix for Ruby 2.7.

**Comment by YingjieGuan** [comment]
+1, I can not upgrade to 3.0

**Comment by danielh27** [comment]
+1 cannot update to 3.0

**Comment by AustinLinares** [comment]
+1 cannot update to 3.0

**Comment by tholu** [comment]
This is still a problem, can this be reopened?

**Comment by Gazzonyx** [comment]
I'm in the same boat - didn't expect a minor release to break compat to a major version of the runtime.  I'm doing a POC to show how we can use open-telemetry and dist. tracing across our org and reworking the gems to get my microservice from 2.7.8 (due to deps I'm stuck with because of licensing for the libs I'm using and the server versions they support ) to Ruby 3.x.


Could we get a final release that doesn't break runtime compat before dropping support for Ruby 2.7?

**Comment by tlubz** [comment]
I have a temporary workaround for now. You can add this to e.g. a rails initializer/rackup whatever:

```ruby
class HackRackEnvGetter < OpenTelemetry::Context::Propagation::RackEnvGetter
  def get(carrier, key)
    carrier[to_rack_key(key)] || carrier[key]
  end

  protected

  def to_rack_key(key)
    ret = +"HTTP_#{key}"
    ret.tr!('-', '_')
    ret.upcase!
    ret
  end
end

RACK_ENV_GETTER = HackRackEnvGetter.new

OpenTelemetry::Common::Propagation.instance_eval do
  def rack_env_getter
    RACK_ENV_GETTER
  end
end
```
