### ISSUE TITLE
Push `opentelemetry-exporter-otlp-grpc` gem to ruby gems

### ISSUE THREAD

**Issue by arikarim** [open-telemetry/opentelemetry-ruby#1584]
We have a problem of not being able to get `opentelemetry-exporter-otlp-grpc` as a gem on ruby gems.

**Description**

Currently we can not use opentelemetry with grpc and ruby as there is not any gems that would support it.
so please do us a favor and publish it to ruby gems as the  gem is already working but can only be used like so for  now:
`gem 'opentelemetry-exporter-otlp-grpc', git: 'https://github.com/open-telemetry/opentelemetry-ruby.git', branch: 'main', glob: 'exporter/otlp-grpc/opentelemetry-exporter-otlp-grpc.gemspec'`

**Comment by arielvalentin** [comment]
Thanks for your feedback!

One of the challenges we face is not having any dedicated maintainers of the gRPC exporter, which is largely the reason we haven't published it.

We also do not have a critical mass of users who've requested support for gRPC; IIRC you'll be the second. 

I think if we could have dedicated maintainers who could handle and triage incoming bug reports and perform regular maintenance then I think the SDK maintainers would likely be willing to publish the gem. 

Since you are a user of the gRPC exporter, would you be interested in helping with maintenance?

**Comment by robertlaurin** [comment]
If you're interested in getting the gem published there's a issue describing some of the work needed to get it to that point https://github.com/open-telemetry/opentelemetry-ruby/issues/1585
