### ISSUE TITLE
Probability sampler only respects parent if it sampled

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-ruby#186]
https://github.com/open-telemetry/opentelemetry-ruby/blob/master/sdk/lib/opentelemetry/sdk/trace/samplers/probability_sampler.rb#L55

It looks like the probability sampler tries to use the parent's behavior if a parent span context exists, but it has a bug where if the parent sampled is `false` it will decide again.

**Comment by mwear** [comment]
This does look like a problem. Thanks for reporting!

**Comment by fbogsany** [comment]
The [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#built-in-samplers) and [OTEP](https://github.com/open-telemetry/oteps/blob/master/text/0006-sampling.md) are inconsistent here, and the OTEP is more explicit, so I'm inclined to trust the OTEP.

The spec says:
> - The default behavior should be to trust the parent SampledFlag. However there should be configuration to change this.
> - The default behavior is to apply the sampling probability only for Spans that are root spans (no parent) and Spans with remote parent. However there should be configuration to change this to "root spans only", or "all spans".

This is self-contradictory, since the first point says we should "trust" the parent SampledFlag, while the second says we should apply the sampling probability for Spans with remote parent.

The OTEP says:
> - Allows users to configure to ignore the parent SampledFlag.
> - Allows users to configure if probability applies only for "root spans", "root spans and remote parent", or "all spans".
>    - Default is to apply only for "root spans and remote parent".
>    - Remote parent property should be added to the SpanContext see specs PR/216
> - Sample with 1/N probability
>
> **Root Span Decision:**
>
> |Sampler|RecordEvents|SampledFlag|
> |---|---|---|
> |Probability|`Same as SampledFlag`|`Probability`|
>
> **Child Span Decision:**
>
> |Sampler|RecordEvents|SampledFlag|
> |---|---|---|
> |Probability|`Same as SampledFlag`|`ParentSampledFlag OR Probability`|

The last decision table says we should apply the sampling probability if the `ParentSampledFlag` is false.

The [Go implementation](https://github.com/open-telemetry/opentelemetry-go/blob/e0406dd3eb7aa826aba19287e8a14ca016bf8578/sdk/trace/sampling.go#L64-L74) applies the same logic, although it does not permit the degree of configurability suggested by either the spec or the OTEP.

**Comment by fbogsany** [comment]
The spec has changed to have [the probability sampler (trace id ratio based sampler)](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#traceidratiobased) ignore the parent’s sampled flag and to have a [parent based sampler](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#parentbased) act as a wrapper to respect the parent’s sampled flag. We implemented this in #322 and #330.
