### ISSUE TITLE
resource autodetection

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#230]
It would be nice to have resource auto-detection, similar to what exists in opentelemetry-js. The logic was largely ported from OpenCensus Node: 

https://github.com/open-telemetry/opentelemetry-js/pull/899

There is little to no specification for it at this time, there is a related issue:
https://github.com/open-telemetry/opentelemetry-specification/issues/535

**Comment by fbogsany** [comment]
@robertlaurin can you please comment here so I can assign this one to you? 😄

**Comment by robertlaurin** [comment]
Hey 👋, I'm going to work on this :)

**Comment by fbogsany** [comment]
I referenced the OpenTelemetry Collector's implementation of resource auto-discovery on today's SIG call. Turns out it's a little more Kubernetes-specific (and much more complicated) than I thought: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/k8sprocessor. I'm not sure how much we can usefully extract from it.

**Comment by fbogsany** [comment]
Do we consider this fixed by #263 or do we want to leave this open to add resource detection for platforms other than GCP?

**Comment by fbogsany** [comment]
From last week's call, we decided to close this with #263 and open new issues for platforms other than GCP.
