### ISSUE TITLE
Inject correlations in rack adapter

### ISSUE THREAD

**Issue by Asafb26** [open-telemetry/opentelemetry-ruby#279]
Hello,
I'm in the middle of research about context propagation implementation in my business.
one of my requirements is to inject business values across the span (user_id, user_agent, ab test allocations, etc).
As far as I understand the specifications - those should be injected as CorrelationContext.
I'm using your Rack Adapter and wonder how to inject those values with the predefined logic of this adapter as I can't find it in the current implementation

Thanks

**Comment by fbogsany** [comment]
Our current implementation is not up-to-date with the spec. We currently use the W3C `Correlation-Context` header instead of the [`otcorrelations`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/correlationcontext/api.md#header-name) header.

You can find the implementation of CorrelationContext extraction here: https://github.com/open-telemetry/opentelemetry-ruby/blob/master/api/lib/opentelemetry/correlation_context/propagation/text_extractor.rb

For Rack, we look for the `HTTP_CORRELATION_CONTEXT` header: https://github.com/open-telemetry/opentelemetry-ruby/blob/0af11280508c8f754bab54a9d2cb482f76983282/api/lib/opentelemetry/correlation_context/propagation.rb#L20-L22

This capability is installed by default in the SDK:
https://github.com/open-telemetry/opentelemetry-ruby/blob/0af11280508c8f754bab54a9d2cb482f76983282/sdk/lib/opentelemetry/sdk/configurator.rb#L136-L141

**Comment by Asafb26** [comment]
Thanks, how can I add my own correlations (current_user.id, allocations, etc) while using the rack adapter to create the context?

**Comment by Asafb26** [comment]
this is how I did it, for now, I'm not sure if that the correct way to do it:
```ruby
get '/test' do
  context = OpenTelemetry.correlations.build_context do |correlations|
    correlations.set_value('user_id', '123')
    correlations.set_value('user_agent', 'test')
   end

   OpenTelemetry::Context.current = context
##### logic ####
```

**Comment by fbogsany** [comment]
I might defer to @mwear for this.

**Comment by mwear** [comment]
@Asafb26 Your example is on the right track. Manually setting the context like that will likely get you into trouble, use `with_current` instead. We can look into adding better documentation (setting it as `@api private` or possibly even removing the writer). Try this instead:

```ruby
get '/test' do
  context = OpenTelemetry.correlations.build_context do |correlations|
    correlations.set_value('user_id', '123')
    correlations.set_value('user_agent', 'test')
   end

   OpenTelemetry::Context.with_current(context) do
     ##### logic ####
     # http requests in this block will have your correlations.
  end
```

**Comment by Asafb26** [comment]
@mwear Thank you.
I understand that we cannot create a setter for that because we must handle the context once the block executed, my concern is that my entire business logic must be under this block which can be a single point of failure
