### ISSUE TITLE
Support standard environment variables in SDK

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-ruby#337]
See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md

**Comment by mwlang** [comment]
I can help with this.  Looking through what's in the codebase now,  the first thing obvious I saw was the environment variables for enabling/disabling adapters.  

Right now, for example, Sinatra would be enabled/disabled via `OPENTELEMETRY_ADAPTERS_SINATRA_ENABLED`. 

Per the specs, it looks like this would change to be `OTEL_RUBY_ADAPTERS_SINATRA_ENABLED`

Is this a correct interpretation?

**Comment by fbogsany** [comment]
> Per the specs, it looks like this would change to be `OTEL_RUBY_ADAPTERS_SINATRA_ENABLED`

We've changed the name of Adapters to Instrumentation, so this should be `OTEL_RUBY_INSTRUMENTATION_SINATRA_ENABLED`.

**Comment by mwlang** [comment]
Ok, will make it so.  That raises a question: is the plan also to rename all "adapter" classes to "Instrumentation". If so, and it's not being tackled I can do that as well (in another PR).

**Comment by fbogsany** [comment]
> Ok, will make it so. That raises a question: is the plan also to rename all "adapter" classes to "Instrumentation". If so, and it's not being tackled I can do that as well (in another PR).
> 
> ADDENDUM: I see now that it's more involved than a simple renaming of class hierarchies since gems are also separately built along the way.

I believe we already did that in #285. Did we miss something?

**Comment by mwlang** [comment]
> I believe we already did that in #285. Did we miss something?

So strange!  I still have an ./adapters folder despite syncing my fork to upstream and so that was naturally where my first hits on searching for Sinatra, etc. to review how it was currently implemented.  I don't quite get why a `git status` isn't showing this folder as untracked, nor why a `git rebase upstream/master` failed to remove it (`upstream` for me is the _this_ repo)

Either way, removing `adapters` folder still passes all local tests.

**Comment by mwlang** [comment]
I went through the specs and through the entire code looking for usage of environment variables. A few key recent changes looks to have addressed all the Environment naming changes.  The only ones left are internal to the project itself such as `OPENTELEMETRY_RELEASES_ENABLED` and `OPENTELEMETRY_RUBYGEMS_API_KEY` which would also presumably require changes to the repo set up to keep from breaking github actions and the release process.

**Comment by fbogsany** [comment]
> The only ones left are internal to the project itself such as `OPENTELEMETRY_RELEASES_ENABLED` and `OPENTELEMETRY_RUBYGEMS_API_KEY` which would also presumably require changes to the repo set up to keep from breaking github actions and the release process.

Thanks @mwlang! These don't need to change, since they only relate to the build process and not to the released gems.

**Comment by fbogsany** [comment]
I don’t think we handle `OTEL_LOG_LEVEL` yet, or `OTEL_PROPAGATORS`.

**Comment by mwlang** [comment]
Ok, I'll look for these specifically and come back with either an update what I find or PR as needed to resolve.

**Comment by mwlang** [comment]
If I am understanding how `OTEL_PROPAGATORS` is spec'd, a user can supply a comma-separated list of propagators as strings to control the values.  Yet, the Configurator's interface (specifically, `:http_extractors`, `:http_injectors`, `:text_map_extractors`, and `:text_map_injectors`) for setting these propagators expects Ruby classes and not strings.  

I'm unclear what we'd like to do in the Ruby implementation since we have the four separately configurable properties whereas the environment variable approach is a single source presumably controls all four properties in tandem.

Three approaches immediately apparent:

1. The above four properties, which are expecting only an Array of Ruby classes, needs to also allow setting by string values so a user can configure by specifying `"tracecontext,baggage"` (for example).  A user setting this up manually in a configuration would do something like:

```ruby
# currently implemented!
OpenTelemetry::SDK::Configurator.new.tap |config|
  config.http_injectors = [
    OpenTelemetry::Trace::Propagation::TraceContext.text_map_extractor,
    OpenTelemetry::Baggage::Propagation.text_map_extractor
   ]
  config.http_extractors = [
    OpenTelemetry::Trace::Propagation::TraceContext.text_map_extractor,
    OpenTelemetry::Baggage::Propagation.text_map_extractor
   ]
# ...
end
```

This enhancement would also allow:

```ruby
OpenTelemetry::SDK::Configurator.new.tap |config|
  config.http_injectors = "tracecontext,baggage"
  config.http_extractors = "tracecontext,baggage"
end
```
_OR_

2. We keep the interface exactly as-is, but implement an additional step in initialization that takes precedence over `default_http_extractors`, `default_http_injectors`, `default_text_map_injectors`, `default_text_map_extractors`.  That is, if `OTEL_PROPAGATORS` exists, then Arrays suitable to all four properties is rendered.  If the ENV variable is absent, then `nil` is rendered and we fallback to the current defaults for each property (behavior is otherwise the same as today's implementation).  In other words, something like:

```ruby
def env_http_injectors
 ENV["OTEL_PROPAGATORS"].to_s.downcase.split(",").select do |name|
    { "tracecontext" => OpenTelemetry::Trace::Propagation::TraceContext.rack_extractor,
      "baggage" => OpenTelemetry::Baggage::Propagation.rack_extractor
     }
end

# ... as well as env_http_extractors, env_text_map_injectors, and env_text_map_extractors ...

def configure_propagation
  OpenTelemetry.propagation.http = create_propagator(
    @http_injectors || env_http_injectors || default_http_injectors,
    @http_extractors || env_http_extractors|| default_http_extractors)
  OpenTelemetry.propagation.text = create_propagator(
    @text_map_injectors || env_text_map_injectors || default_text_map_injectors,
    @text_map_extractors || env_text_map_extractors || default_text_map_extractors)
```

_OR_

3. We leave the four properties completely alone and introduce configuring through an all-new `propagators` property.  This will serve to set up all four components (http injector/extractor and text_map injector/extractor) with the specified propagators.

```ruby
OpenTelemetry::SDK::Configurator.new.tap |config|
  config.propagators = "tracecontext,baggage"
end
```

The concern here is which wins when user sets `propagators` and any of the four specific properties and how often will the user get it wrong, even if we're clearly documenting how to properly configure with all the options?

Personally, and without fully knowing the use-cases for where ability to control all four independently, I would advocate simplicity and eliminate the four properties and replacing with only the `propagators` property taking a comma-separated string of propagator names.

**Comment by fbogsany** [comment]
Let's punt the `OTEL_PROPAGATORS` env var for now. According to the spec compliance matrix, no other language has implemented it yet. I feel like this has not been adequately specified, so I'd like to see how other languages approach this. Specifically, I *think* we may need to add a propagator registry of some kind, but that's not part of the spec.

**Comment by fbogsany** [comment]
We’ve done as much as we’re going to for now. We can revisit OTEL_PROPAGATORS in a later issue.
