### ISSUE TITLE
Add option to flush tracer on SIGINT / SIGTERM

### ISSUE THREAD

**Issue by johnnyshields** [open-telemetry/opentelemetry-ruby#473]
Currently, if you SIGINT or SIGTERM a process, there is a chance that pending spans may not be written (esp when using BatchSpanProcessor)

We should add a configuration option which traps these signals, forces a flush, then re-raises the signal

It would look something like:

```
      trap('TERM') do
        tracer_provider.flush
        raise SignalException, 'TERM'
      end

      trap('INT') do
        tracer_provider.flush
        raise SignalException, 'INT'
      end
```

**Comment by fbogsany** [comment]
For now, the specifics of signal handling are up to application authors. We should clearly document `TracerProvider#shutdown` (rather than `flush`) and suggest its use with signal handling. The spec says nothing about signal handling at the moment; and it is difficult to come up with reasonable default behaviour, especially around timeouts (see #341 for work to add a timeout parameter to `shutdown` and `flush`).
