### ISSUE TITLE
rename default branch to main

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-ruby#576]
As discussed at the SIG meeting this morning, we'd like to rename the default branch to main.

Related community issue:
https://github.com/open-telemetry/community/issues/402

Here is a document that summarizes the steps: https://docs.google.com/document/d/1lkA0Re3vWfqXmuYLhL93Y6ABR27Sg6DzPcwi4kPXj0Y/edit

**Comment by arielvalentin** [comment]
👋🏼 Something to consider would be to use the `$default_branch` macro in actions workflows as opposed to using explicit branch names.

There are more details available here:

https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/

**Comment by dazuma** [comment]
@arielvalentin Thanks for the tip! I'll look into where we might be able to use that. (However, it might be the case that most of our workflows should potentially work on multiple branches besides the default, if we have release/stable branches.)

**Comment by arielvalentin** [comment]
In those cases release and stable branches can still be referred to by name since Actions workflows allow for one to register multiple branches at a time.
E.g. of what a push looks likes incorporating both:

```yaml
on:
  push:
    branches:
      - $default_branch
      - "releases/**"
      - "stable/**"
```

The `$default_branch` macro ￼will come in handy in the rename. 


- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags

Hope that helps.

**Comment by bogdandrutu** [comment]
@mwear should this be closed? Looks like the branch is changed

**Comment by dazuma** [comment]
Yes, closing.

**Comment by mwear** [comment]
Thanks @dazuma 🙏.
