### ISSUE TITLE
How can I have per instrumentation propagators?

### ISSUE THREAD

**Issue by hmadison** [open-telemetry/opentelemetry-ruby#605]
Hi,

While looking at the Kafka implementation I noticed that `OpenTelemetry.propagation.inject` is a share singleton across all of the running instrumentations. I'm wondering if its possible to have per instrumentation propagators in situations where there are [different trace context](https://www.w3.org/TR/trace-context-protocols-registry/) protocols.

To the best of my understanding, opentelemtry-ruby would need to have some kind of mechanism for this to be able to support AMQP and MQTT trace contexts following the W3 standard. It also appears, with regards to Kafka, that the current implementation of trace context instrumentation is undefined since there is no registry entry for the protocol? 

Thanks,
Hunter

**Comment by fbogsany** [comment]
Thanks for the reference. From that, I see that protocol-specific (MQTT, AMQP, HTTP, etc.) encodings are defined. This should be handled with protocol-specific [Getters](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/api/lib/opentelemetry/context/propagation/text_map_getter.rb) and [Setters](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/api/lib/opentelemetry/context/propagation/text_map_setter.rb) rather than per instrumentation propagators, although you could choose instead to add a configuration option to instrumentation to override the propagator.

> with regards to Kafka, that the current implementation of trace context instrumentation is undefined since there is no registry entry for the protocol

That's an interesting point. My knowledge of Kafka is not that deep, but if this is a problem, it presumably affects all OTel language implementations that instrument Kafka. It should be brought up at the spec level. If you have sufficient context, can you please open an issue in the https://github.com/open-telemetry/opentelemetry-specification repo?

**Comment by hmadison** [comment]
Thanks for the guidance! I'll work on getting something written up for the specification repo.

Hunter
