### ISSUE TITLE
Same `trace_id` generated for many requests

### ISSUE THREAD

**Issue by drogus** [open-telemetry/opentelemetry-ruby#670]
I'm using rack instrumentation with a rails application and I'm seeing a weird behavior. On one of the routes a `trace_id` can be often assigned to multiple requests. It isn't always the same `trace_id`, but from time to time there is a bunch of requests (often hundreds) that have the same `trace_id`. It happens usually in a relatively small time frame (as far as I can tell up to 10-20 minutes). As far as I know the request doesn't contain any special headers, just the usual stuff like `Accept`, `Content-Type` and `Authorization`.

My thinking is that for some reason Rack instrumentation decides to put the same `trace_id` on multiple requests, but I don't really see anything that could cause it. Is there anything that Rack instrumentation might look at before generating a trace id? Or does it sound like some kind of bug? Maybe concurrency based?

**Comment by drogus** [comment]
After further investigation it turns out that most of this calls are done with a `rest-client` gem, but then there are also cases where a root span is "organic" (ie. a web browser request) and the rest of the requests with the same trace id are done with a rest-client.

**Comment by ahayworth** [comment]
> Is there anything that Rack instrumentation might look at before generating a trace id?

It inspects the Rack env to see if it should be setting the parent span context for this request (ie: the inbound request had trace propagation headers of some kind). But otherwise, no.

> Or does it sound like some kind of bug? Maybe concurrency based?

It certainly does sound weird. If you have a way to reproduce this, it's probably something worth investigating! The way Rails does it with their [executable test cases](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) I think would be useful in this instance. 😄 

Notably, though - if you're using Unicorn as your Rack server, you might try upgrading to the [just-released 6.0.0](https://github.com/defunkt/unicorn/commit/3ed7dfc218475c9b6b95f62e0eba6975ecd52e45) to see if that clears up any issues. Unicorn was re-using the same env hash prior to that version, and thread-unsafe code could tickle [really dangerous bugs](https://github.blog/2021-03-18-how-we-found-and-fixed-a-rare-race-condition-in-our-session-handling/) with that env hash re-use.

**Comment by drogus** [comment]
> It inspects the Rack env to see if it should be setting the parent span context for this request (ie: the inbound request had trace propagation headers of some kind). But otherwise, no.

Is there a list of those headers somewhere? The only thing I could find are a few headers in one of the tests: https://github.com/open-telemetry/opentelemetry-ruby/blob/6c48b90b7ee3e2cc529ea31ab4c1e2d34ed4ddb3/api/test/opentelemetry/context/propagation/rack_env_getter_test.rb#L16-L18

**Comment by ahayworth** [comment]
> Is there a list of those headers somewhere?

@drogus not exactly, because OpenTelemetry SDKs allow you to propagate context in multiple ways - so the possible values get a little buried in layers of abstraction. 😄  But here are the default ones:
- W3C trace context (one of the defaults): `trace-id` and `trace-parent` (ref: https://www.w3.org/TR/trace-context/#traceparent-header-field-values)
- W3C baggage (one of the defaults): `baggage` (ref: https://w3c.github.io/baggage/)

These are not default, but could be enabled if you have configured them in your SDK (via the `OTEL_PROPAGATORS` env variable, perhaps):
- b3 single-header: `b3` (ref: https://github.com/openzipkin/b3-propagation#single-header)
- b3 multi-header: `X-B3-TraceId`, `X-B3-ParentSpanId`, `X-B3-SpanId`, `X-B3-Sampled` (ref: https://github.com/openzipkin/b3-propagation#multiple-headers)
- opentracing: `ot-tracer-traceid`, `ot-tracer-spanid`, `ot-tracer-sampled`, `ot-tracer-baggage` (ref: https://github.com/open-telemetry/opentelemetry-ruby/blob/main/propagator/ottrace/lib/opentelemetry/propagator/ottrace.rb#L23-L26)
- jaeger: `uber-trace-id` (ref: https://github.com/open-telemetry/opentelemetry-ruby/blob/main/propagator/jaeger/lib/opentelemetry/propagator/jaeger.rb#L31)

Sorry that's not the simplest answer 😆 ! I think if you're using a default installation you really only need to look for the W3C headers I listed above, and not the others. But I wanted to include them for completeness (and in case someone else comes looking for header names).

**Comment by fbogsany** [comment]
For clarity, `traceparent` is the header name for W3C trace context propagation.

**Comment by drogus** [comment]
Thanks for all the info! It would be nice to have a way to inspect it in runtime, ie. some kind of method of saying: give me all the headers that currently installed extractors will look at.

**Comment by fbogsany** [comment]
Once #638 merges, you'll be able to get the list of header keys to be inspected by installed propagators using:
```ruby
OpenTelemetry.propagation.fields
```

**Comment by drogus** [comment]
Awesome, thanks! I'm going to close for now. If I find any issue in OpenTelemetry itself I will reopen, but I think it might be a matter of using one of these headers in the rest client.
