### ISSUE TITLE
EOFError when exporting to Jaeger OTLP port

### ISSUE THREAD

**Issue by alexgenco** [open-telemetry/opentelemetry-ruby#787]
I'm trying to use `opentelemetry-exporter-otlp` to export traces to the OTLP port of a local Jaeger instance. I'm aware there is a Jaeger-specific exporter, but I'm only using Jaeger locally to test OTLP export, since we use a non-Jaeger OTLP collector in production.

I created a gist for the minimal repro case: https://gist.github.com/alexgenco/8e18aa119b891ea6d69e7359e05984c1

```
docker-compose up -d
ruby repro.rb
```

You should see the EOF errors logged (emitted from [this `rescue`](https://github.com/open-telemetry/opentelemetry-ruby/blob/76ca7fe5255691a525a5daa886074041c71c2e2f/exporter/otlp/lib/opentelemetry/exporter/otlp/exporter.rb#L209)):

```
...
I, [2021-06-04T11:07:22.907765 #13621]  INFO -- : [:record_value, ["otel.otlp_exporter.request_duration"], {:value=>14.190000016242266, :labels=>{"status"=>"unknown"}}]
I, [2021-06-04T11:07:22.907830 #13621]  INFO -- : [:add_to_counter, ["otel.otlp_exporter.failure"], {:labels=>{"reason"=>"eof_error"}}]
...
E, [2021-06-04T11:08:04.228154 #13977] ERROR -- : OpenTelemetry error: Unable to export 1 spans
```

I've tried this with [the analogous OTLP exporter in `opentelemetry-go`](https://github.com/open-telemetry/opentelemetry-go/tree/aed458026f8171751eb415f37f2815629fcd0848/exporters/otlp) and it works, with traces correctly showing up in the Jaeger UI. So it seems like this `jaegertracing/opentelemetry-all-in-one` image is otherwise capable of ingesting OTLP protobufs on this port.

**Comment by ahayworth** [comment]
Hi @alexgenco - unless I'm mistaken, I think the port you're using in the gist (`55680`) implies OTLP-over-GRPC; and the Ruby SDK [doesn't support that](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#exporters). Yet, anyways - help wanted. 😄 

We only support OTLP/HTTP at this time.

**Comment by alexgenco** [comment]
Ah OK that explains it. Is OTLP over HTTP a common use case? It looks like neither Jaeger nor Honeycomb Refinery (the collector we use in deployed envs) support it.

I'll close this, and possibly look into adding OTLP/gRPC support at some point if it's not already in the works.

**Comment by ahayworth** [comment]
> Is OTLP over HTTP a common use case?

I think it depends on your ecosystem - gRPC support in Ruby is not fantastic, and so I don't often find projects that use it in the Ruby ecosystem. I believe at least the JS browser SDK also cannot support gRPC, but I could be mis-remembering it.

I think we'd definitely like to have it, it's just not been a task we've prioritized since OTLP/HTTP support is present in the collector (as well as some vendor collectors, such as the LightStep satellites).

I suppose I would say that OTLP/HTTP is not as commonly used or implemented in other language SDKs, but it's not completely unheard of. 😄 

We'd definitely appreciate the contribution if you choose to do so! Let us know how we can help, if you do decide to take it on.

**Comment by alexgenco** [comment]
> OTLP/HTTP support is present in the collector

Are you referring to https://github.com/open-telemetry/opentelemetry-collector ?

**Comment by ahayworth** [comment]
Indeed!
