### ISSUE TITLE
Explicitly define a NonPropagatingSpan function

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#793]
Correct me if I'm wrong: I believe you are supporting wrapping the `NonRecordingSpan` notion through the no-op API `Tracer`, i.e. in API `Tracer.start_span()` you do:

```ruby
Span.new(span_context: span_context)
```

Effectively wrapping a `SpanContext`. `Span` itself doesn't _seem_ to publicly allow this though:

```ruby
      # @api private
      def initialize(span_context: nil)
```

But we need to offer this publicly. Maybe consider exposing a `Span.wrap(SpanContext)` function?

**Comment by fbogsany** [comment]
[From the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#wrapping-a-spancontext-in-a-span):

> If a new type is required for supporting this operation, it SHOULD NOT be exposed publicly if possible

and:

> This functionality MUST be fully implemented in the API, and SHOULD NOT be overridable

We don't need a new type. Is it enough to remove the `@api private` comment on `initialize`, and fix the method documentation to describe the wrapping use-case, or do you think we need an explicit `Span.wrap(SpanContext)` method?

There's actually a contradiction in the spec, since the first line of [Span Creation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span-creation) states:

> There MUST NOT be any API for creating a Span other than with a Tracer.

Technically, we meet both requirements with the current approach, using `Tracer.start_span`, although it is a little opaque.

**Comment by fbogsany** [comment]
> Technically, we meet both requirements with the current approach, using `Tracer.start_span`, although it is a little opaque

This is no longer true since #795

**Comment by fbogsany** [comment]
I tinkered with this a bit this morning and concluded that we cannot implement the `NonRecordingSpan` functionality without violating this requirement:
> There MUST NOT be any API for creating a Span other than with a Tracer.

Specifically, we need to create a `non_recording_span` from Propagators, which do not have access to a Tracer instance, unless we require Propagators to each have their own Tracer instance.

**Comment by carlosalberto** [comment]
Hey @fbogsany 

> There MUST NOT be any API for creating a Span other than with a Tracer.

That means an _actual_ `Span`, i.e.`NonRecordingSpan` is simply a decorator that does not add new telemetry data (we should probably clarify this in the Spec too ;) )

**Comment by fbogsany** [comment]
Thanks @carlosalberto - I moved the method to the `OpenTelemetry::Trace` module.
