### ISSUE TITLE
Consider making SDK NoopSpanProcessor/NoopSpanExporter private

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-ruby#819]
Similar situation as `NoopTextMapPropagator`. Maybe technical reasons to expose them as well? i.e. it's not really bad if they are public, just (probably) not needed.

**Comment by fbogsany** [comment]
We use duck typing rather than inheritance for span processors. The `NoopSpanProcessor` is what we point at as the primary documentation for this part of the SDK's API. It is explicitly not intended to be subclassed.

I think it might be cleaner to rename this to `SpanProcessor` and leave it exposed. It may also be more appropriate to make it a `module` rather than a `Singleton` class.

`NoopSpanExporter` is similarly used to document the `SpanExporter` duck type. It is not actually used by the SDK, other than in tests. Here, the code is intended as a template for writing new span exporters (specifically the lifecycle of the exporter). I'm not sure what's cleanest here - possibly again just renaming it to `SpanExporter` but keeping it as a `class` and documenting that it is not intended to be subclassed.
